### PR TITLE
Change highlight colour for monsters on map

### LINKED ISSUE #53: Highlight monster bodies with a color different than the player's

### PR DESCRIPTION
**Pull request by dread-uo**
Highlight monsters using red decorator.

Closes #53.

### CODE REVIEW

**Comment by dread-uo** [comment]
I hard-coded the highlight color for enemies. Do you prefer to have the color as a property of the map instead?

**Comment by dread-uo** [comment]
ping @OrenjiAkira , @Kazuo256 , @rafaeljpc

**Comment by OrenjiAkira** [comment]
i think this should be merged first, then the other two pull requests
if there are adjustments we can do it on top of it

**Comment by OrenjiAkira** [comment]
@Kazuo256

**Pull request merged**
