### PR TITLE
This is madness

### PR DESCRIPTION
**Pull request by Kazuo256**
This PR:

1. Implements a debug GUI framework with stackable menus (toggle debug mode with F1)
2. Moves the game's database to JSON using dkjson
3. Allows the debug GUI to manipulate database entries (add, delete and edit)

**The best way to see the changes is to actually play it!!!**

### CODE REVIEW

**Comment by OrenjiAkira** [comment]
what the actual fuck this is so fucking cool

**Comment by Kazuo256** [comment]
The next I wanted to do here was to add and delete database entries through the GUI. I'll probably stop there.

**Comment by OrenjiAkira** [comment]
it's so pretty and juicy i cannot even

**Comment by Kazuo256** [comment]
Done. You guys can merge this now if you want.

**Pull request merged**
