### PR TITLE
Fix camera centralisation and pixel snap issues

### PR DESCRIPTION
**Pull request by OrenjiAkira**
The PR no one asked for

### CODE REVIEW

**Comment by Kazuo256** [comment]
Was the solution to use CAM:lockPosition()? Why did you have to re-implement CAM:attach()?

**Comment by OrenjiAkira** [comment]
The `lockPosition()` method does exactly the same as moving the camera to where we want with smoothness. I just thought it would be simpler to delegate the animation to hump.

It’s not the solution, however. The solution was to reimplement the attach method so it would round the translate values _only_ when actually translating, but not the position vector itself (which stays as a float value).

To be honest, though, I got the solution from [this](https://github.com/nkorth/hump/commit/a98c04e9e077ad5200207cd287be576ce599cf6b), which came up when I was reading [this thread](https://www.google.com.br/amp/s/amp.reddit.com/r/love2d/comments/6zpse1/hump_camera_making_my_game_blurry/)

**Comment by OrenjiAkira** [comment]
Also since I do not have a computer that reproduces the glitch, please test it yourself so I know that it’s really fixed.

**Comment by Kazuo256** [comment]
It looked fine here.

**Pull request merged**
