### PR TITLE
Laser beam card

### PR DESCRIPTION
**Pull request by dread-uo**

### CODE REVIEW

**Comment by Kazuo256** [comment]
Is the PR ready? I'm gettin a `Identifier not found: CENTER` at `laser_beam.gd:51` here.

**Comment by Kazuo256** [comment]
Also, if you want to, you can implement this card by adding a new type of OPTION to cards instead of using targets (the new OPTION would cast card in a direction instead of at some position). Don't worry it too much about it though.

**Comment by dread-uo** [comment]
Sorry, forgot that last commit ¯\_(ツ)_/¯
I liked that OPTION alternative, it seems useful for future cards. I might implement it and refactor this later. Do you think the dynamic aoe feature is worth keeping?

**Comment by Kazuo256** [comment]
> Do you think the dynamic aoe feature is worth keeping?

Absolutely =)

**Pull request merged**
