### PR TITLE
Add attributes to actors

### PR DESCRIPTION
**Pull request by OrenjiAkira**
pretty straightfoward

### CODE REVIEW

**Comment by Kazuo256** [comment]
There is also the `get_attribute` operator to fix.

**Comment by OrenjiAkira** [comment]
what?

**Comment by Kazuo256** [comment]
In `game/domain/operators/get_attribute.lua`. There's a `FIXME` pointing where the attributes should be used.

**Comment by OrenjiAkira** [comment]
ok, but what is it supposed to do? is it used anywhere so i can see it?

**Comment by Kazuo256** [comment]
It's used in the `SHOOT` action if I'm not mistaken.

**Comment by OrenjiAkira** [comment]
ok, i have no idea of what is going on with that code

**Comment by Kazuo256** [comment]
OK, maybe the `take_damage` effect better illustrates how to write the actual code. Did you also look at the `SHOOT` action through devmode?

The idea is that the fields specified in the operator's schema are available in the `params` argument of the `OP.process()` function. In the case of `get_attribute` it determines which attribute to get. All you have to do is return the corresponding attribute value from the actor the function receives.

**Comment by OrenjiAkira** [comment]
like this?

**Comment by Kazuo256** [comment]
Pretty much. Maybe we'll eventually add something to make sure a weird getter isn't called.

**Pull request merged**
