### PR TITLE
Controller Refactoring

### PR DESCRIPTION
**Pull request by rafaeljpc**

### CODE REVIEW

**Comment by rafaeljpc** [comment]
@Kazuo256 done

**Comment by Kazuo256** [comment]
I tested the branch and found a bug: when you cast the "teleport" card and try to move the target, the player character moves too.

**Comment by rafaeljpc** [comment]
I'll see that O.o

**Comment by rafaeljpc** [comment]
@Kazuo256 I pulled the branch to my Home-PC and it worked properly.

**Comment by Kazuo256** [comment]
Yes, indeed. I tried again and it seemed to work now O.o

But then I found something else. When you are targeting something, pressing ESC should cancel the targeting mode, but in this branch it closes the game altogether.

**Comment by rafaeljpc** [comment]
Okay I'll fix it

**Comment by rafaeljpc** [comment]
The cursor_controller and main_controller were both handling the cancel event, I fixed it. But I think that the exit should be triggered by a popup before actually close the game. Maybe in another milestone

**Comment by dread-uo** [comment]
About the popup, godot can handle it: http://docs.godotengine.org/en/latest/tutorials/engine/handling_quit_requests.html.

**Comment by Kazuo256** [comment]
Okay, so now you only need to rebase this branch so we can merge it =).

**Pull request merged**
